import type { Metadata } from "next";
import "../globals.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { options } from "../api/auth/[...nextauth]/options";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/Providers/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options)
  return (
    <html lang="en" className="h-full">
      <body className="font-sans bg-milk h-full" >
        <SessionProvider session={session}>
          <section className="flex flex-col min-h-full">
            <Navbar />
            <main className="relative flex-auto mx-[150px] my-[20px] text-night">
              {children}
            </main>
            <Footer />
          </section>
        </SessionProvider>
      </body>
    </html>
  );
}
