import type { Metadata } from "next";
import "../globals.scss";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";
import React from "react";

import { Abel } from "next/font/google"
const abel = Abel({
  weight: '400',
  subsets: ['latin'],
})

import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Blueprint",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`font-sans bg-milk h-full ${abel.className}`} suppressHydrationWarning={true}>
        <Providers>
          <section className="flex flex-col min-h-full">
            <Navbar />
            <main className="relative flex-auto mx-[150px] my-[20px] text-night flex">
              {children}
            </main>
            <Footer />
          </section>
        </Providers>
      </body>
    </html>
  );
}
