import type { Metadata } from "next";
import "../globals.scss";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="font-sans bg-milk h-full" suppressHydrationWarning={true}>
        <Providers>
          <section className="flex flex-col min-h-full">
            <Navbar isLoginPage={true} />
            <main className="relative flex-auto text-night">
              {children}
            </main>
            <Footer />
          </section>
        </Providers>
      </body>
    </html>
  );
}
